### ISSUE TITLE
Potential misleading cloudInitNoCloud/networkData example in startup scripts

### ISSUE THREAD

**Issue by olberger** [kubevirt/user-guide#243]
I've been trying to replicate a cloud-init config for a VMI following:
https://github.com/kubevirt/user-guide/blob/master/creating-virtual-machines/startup-scripts.adoc#cloud-init-network-config-as-clear-text

From my experience, it seems that the Ubuntu 18.04 cloud-init wouldn't like:
```
      - cloudInitNoCloud:
          networkData: |
            network:
              version: 1
              config:
              - type: physical
              name: enp1s0
              subnets:
                - type: dhcp
```
But that one worked:
```
      - cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp1s0:
                dhcp4: true
```
I have the impression that networkData: shouldn't contain a network entry. 

This is a bit confusing wrt other docs instructing how to construct contents of the noCloud.iso... but still...

Hope this helps,
