### ISSUE TITLE
Cloudbase-Init as a provisioning agent for Windows VMs

### ISSUE THREAD

**Issue by ader1990** [kubevirt/user-guide#309]
The startup scripts doc section does not contain information on how a Windows VM can leverage cloudbase-init (https://github.com/cloudbase/cloudbase-init) for achieving the same level of provisioning capabilities of the Linux machines.

Cloudbase-Init is cloud-init's counterpart for Windows, the defacto provisioner for Windows on OpenStack, CloudStack, OpenNebula, packet.net, with support for AWS, Azure, GCE.

From KubeVirt perspective, it supports ConfigDrive and NoCloud metadata support is coming soon.

Cloudbase-Init supports a subset of cloud-config directives, well suited for Windows environments: write_files, set_timezone, set_hostname, ntp, groups, users, runcmd.

More information on the cloud-config support can be found here: https://cloudbase-init.readthedocs.io/en/latest/userdata.html#cloud-config

Example userdata file for adding user / groups and running various commands: 

```yaml
#cloud-config
groups:
  - cloud-users
users:
  - name: Admin
    primary_group: cloud-users
    groups: Administrators
    passwd: StrongPassw0rd
    ssh_authorized_keys:
      - ssh first key
      - ssh second key
runcmd:
 - 'dir C:\\'
 - ['echo', '1']
```

Based on the information from your labs, I made a comprehensive tutorial on how to deploy Kubernetes and all the glue necessary to successfully import, boot, provision and customize a Window  VM, using Cloudbase-Init:

https://github.com/ader1990/windows-openstack-imaging-tools/tree/add_kubevirt_example/Examples/config/kubevirt
