### ISSUE TITLE
Windows 10 VM GPU problem

### ISSUE THREAD

**Issue by Zigko** [kubevirt/user-guide#555]
Hi,

I have tried several windows (server 2012, server 2012 and now windows 10)
I'm trying to pass the GPU for my windows VM, and the firsts attempts the device manager wouldn't recognize the GPU host that is passing with vfio-pci driver.

Currently, I'm using a Windows 10 VM and I can the GPU on the device manager:  
![image](https://user-images.githubusercontent.com/56871305/176730475-70acfa04-43b1-417c-85dc-b1e4a3d98f1a.png)

but is not appearing on the Task Manager:
![image](https://user-images.githubusercontent.com/56871305/176730717-b8afa195-f762-4c65-994f-5eb756f01bf9.png)

When I try to install the NVIDIA drivers the VM crashes with a blue screen giving the next error:
![image](https://user-images.githubusercontent.com/56871305/176730946-9481aaa2-5b20-48eb-9dd5-45852314c66f.png)

---
My VM,PVC and PV:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-volume 
    labels:
      type: local
spec:
    storageClassName: manual 
    capacity:
      storage: 50Gi
    accessModes:
      - ReadWriteOnce 
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/mnt/data" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: windows-10-iso
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows-10-iso
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - cdrom:
              bus: sata
            name: win-iso
            bootOrder: 2
          - disk:
              bus: virtio
            name: harddrive
            bootOrder: 1
          - cdrom:
              bus: sata
              readonly: true
            name: virtio-drivers
            bootOrder: 3
          gpus:
          - deviceName: nvidia.com/gpu_geforce_1660
            name: gpu1
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      volumes:
      - name: win-iso
        containerDisk:
          image: localhost:5000/windows-10-iso:latest
      - name: virtio-drivers
        containerDisk:
          image: kubevirt/virtio-container-disk
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd2

```
---
Is this related to the drivers that were loaded on the VM? 
And what can be the solution?

**Comment by vladikr** [comment]
Some Nvidia products are not supported to be used in virtual machines. Sometimes these are not supported specifically on KVM.
As you can see the issue you are experiencing is related to the nvidia driver itself.

The community versions of kubevirt/libvirt/qemu have a way of allowing turning the KVM signature off.
You may try adding the following to your VMI definition. However, this will not be supported on any vendor distribution of KubeVirt.

```
domain:
  features:
    kvm:
      hidden: true
```
